my_github_handle: git@github.com:ForkMeMaybe

git_config_file: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66353531333030383538343861643131333462323965396339326565393432636232396438636236
          6464333930333263303932303930366133653663316636310a343736623163383932333334383933
          33336334643464613964366361336364366630393334393136323363396530323830313035343866
          6163653932373539370a613034323364663034353065373731366363396664336363393030646233
          34663861316662336535323838326137343033323232323935383135633966346463656533326335
          30393631653866333033653566363738326533643134306234356162303464373230356133343535
          66333534323166623934363764313535343532313865643666393435663133613964663165626161
          31363863366133386337

public_ssh_key_file: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33333063363938306630306561363430383565373235376635323834363935633331663234393463
          3163363063303739346430626263646261653161376235380a386638626165656535343363663339
          34356638306531613761326432646563393635313133303531663063373036386330313665376563
          3366323539366531390a346339303439343466313464343632623263383231393335663764613334
          38316136646433343932616462616562663266303032353362363232376232336534373463366264
          62343239633332333830653733343164653262646262306464323938633939373938353733306333
          62343638316432663266316633326265383237653762663830613766303831316138306130333132
          32303433643934643437653261346536366430613161393032663530643533326362303632363463
          6336

private_ssh_key_file: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61653639333038313937353036626630303162386533306231376465303065346337376162323731
          6265646565386133646539336336663063366137313064660a343832313133356633373338613065
          64653465353833653936616362666432346530376535303365323039393832653331363264633535
          6465636332336265640a386163653066386634663439623561346138396266386462393538326130
          38333731333938356530313562333132313133393930366565363863336630313362323937626536
          33393639383763623734633136663630383530373038313830613630633634316531646162663630
          37343830666236613938663331326338386662383863626536356139303863396238346332343036
          34613264316536616364323233353964323637366334636265626464356636656634386231643761
          32623530626535316263653965653435386534386565663632323837303333306564346564613131
          66633839396531326337316565396263643038363432623861386433643438363835383566376661
          34666263336433326634343961633539383637373631616434633338353330303138373433373638
          35343161313163613430336663383363383337646237323536636233383234343463383963643432
          62363932363130313834386162343630666131643039323261313339663466306663373663646366
          37346433663836383836623733303362366434626131363539373638656362373133646331646138
          62323465646534663163323739306564326536613336383464396633333437316464373930373865
          34626666383862393837303331646336396239666438393537353562343835616666646132646262
          61333866323165393439326635313431333663643631333035313233333562346234656232303930
          39663661376333383636663634643832373266316163306438393033336362333565396664633233
          62366561353530366266356136666165663736356462383166333135323337633434363165383362
          34346331383735316337336337326631323663643862666566333736316534613261653837643661
          37383834656461366464353065303364633234323238666639353965653565343763383637333737
          30633634663234316331396266353532333132353166346264393530666665663365353237363938
          37386632353136323832643834323632303833613636616430613566366132356634343565303233
          32636166633233343235
