[font]
normal = { family = "Iosevka Nerd Font", style = "Regular" }

[window]
padding = { x = 10, y = 10 }
opacity = 0.7
title = "Alacritty"

[cursor]
style = "underline"        # Supported => â–‡ Block, _ Underline, | Beam
vi_mode_style = "Beam"     # Only applicable when in vi mode

[selection]
save_to_clipboard = true

# Dracula color scheme
[colors]
primary = { background = '0x282a36', foreground = '0xf8f8f2' }

[colors.normal]
black = '0x000000'
red = '0xff5555'
green = '0x50fa7b'
yellow = '0xf1fa8c'
blue = '0xcaa9fa'
magenta = '0xff79c6'
cyan = '0x8be9fd'
white = '0xbfbfbf'

[colors.bright]
black = '0x282a35'
red = '0xff6e67'
green = '0x5af78e'
yellow = '0xf4f99d'
blue = '0xcaa9fa'
magenta = '0xff92d0'
cyan = '0x9aedfe'
white = '0xe6e6e6'
